import { Tile } from '../../common/gameState/Tile';

export const tileLookup: {[key: number]: Tile} = {
    0x00: Tile.Floor,
    0x01: Tile.Wall,
    0x03: Tile.Water,
    0x04: Tile.Fire,
    0x0b: Tile.Dirt,
    0x0c: Tile.Ice,
    0x0d: Tile.ForceSouth,
    0x12: Tile.ForceNorth,
    0x13: Tile.ForceEast,
    0x14: Tile.ForceWest,
    0x15: Tile.Exit,
    0x16: Tile.BlueDoor,
    0x17: Tile.RedDoor,
    0x18: Tile.GreenDoor,
    0x19: Tile.YellowDoor,
    0x1a: Tile.IceSouthEast,
    0x1b: Tile.IceSouthWest,
    0x1c: Tile.IceNorthWest,
    0x1d: Tile.IceNorthEast,
    0x22: Tile.ChipGate,
    0x23: Tile.SwitchBlockButton,
    0x24: Tile.CloneButton,
    0x25: Tile.SwitchBlockClosed,
    0x26: Tile.SwitchBlockOpen,
    0x27: Tile.TrapButton,
    0x28: Tile.TankButton,
    0x2b: Tile.Trap,
    0x2f: Tile.Hint,
}